### ISSUE TITLE
co-residents are 2 types: relatives or others

### ISSUE THREAD

**Issue by Mriduladevi** [orkit/Maprom#4]
I just met 3 families in which the head of the household is a married young man, and he lives with his wife and children and his old, widower mother. I was forced to keep the mother as the head of the family, and select the choice of “extended family, two generations, etc”.
Well, I do not know which is the simplest solution and how shall we deal with it, but there are some 10% cases when several people share the same house. I gave you below ALL possible situations. Perhaps one think is to make an attribute co-resident further divided into relative and other. and probably followed by two comment fields where I may select one of these for relative: (bachelor/spinster child, married child, sibling, parent, grandparent, great grandparent, grandson, uncle/aunt, cousin, nephew, parent in-law, son/daughter in-law). And one of these for other (servant, slave, apprentice). However, both, relative and other may to have specifications for name, age, gender, nationality, social status, spouse, child, illness, etc, but not for property, animals, other issues, which they share with the others co-residents.

**Comment by orkit** [comment]
I have now finished adding the co-resident features to the insert-tool (application) and here is a short instruction on how you should use it. I have rushed to finish it for your deadline so there is some things to approve and make better, but for now it’s ready to use.

First when adding a new household you should be particular in adding the following attributes in order not to get an error in validation.
1.	House nr.
2.	Head of household
3.	Name
4.	Age
5.	Civilstatus
These are the compulsory attributes and missing to enter one of them leads to a validation error, which is necessary for entering data in to the database but a bit irritating for the person who enters the data as you sometimes must start from the beginning – I will try to fix this in the future updates but for now you will have to go for it.
To add a co-resident you must first chose an “extended family situation” – this is so that the household can be categorized for statistics calculations later. You can add new categorizes in the dependents menu.
 
When choosing an “extended family situation”, you get a button to add co-residents.
 

You can now add co-residents accordingly to the request you made:
 
Please note! That you have to nest the co-resident correctly.

Parent -> Spouse ->Child ->Child
Sibling->Spouse

**Comment by orkit** [comment]
Julieta: please add at Co/resident, the attributes CIVIL STATUS and ILNESS too! 
- Work in progress

**Comment by orkit** [comment]
Alright, I will work on this comming week. Yes, its possible to to have a direct view into the co-residents table but then only for modification.
